spring:
  elasticsearch:
    rest:
      uris: http://localhost:9200,http://192.168.40.132:9200,http://192.168.40.128:9200
      connection-timeout: 2
      read-timeout: 40
      username: elastic
      password: 123456
#  rabbitmq:
#    host: 192.168.40.132
#    username: lejing
#    password: 123456
#    virtual-host: /lejing
#    template:
#      exchange: LEJING.ITEM.EXCHANGE
